// REDUX ACTION TYPES
export const GETCURRENCYTICKER_REQUEST = 'CURRENCYTICKER_GETCURRENCYTICKER_REQUEST';
export const GETCURRENCYTICKER_SUCCESS = 'CURRENCYTICKER_GETCURRENCYTICKER_SUCCESS';
export const GETCURRENCYTICKER_FAILURE = 'CURRENCYTICKER_GETCURRENCYTICKER_FAILURE';

export const GETCURRENCYDATABYID_REQUEST = 'CURRENCYDATA_GETCURRENCYDATABYID_REQUEST';
export const GETCURRENCYDATABYID_SUCCESS = 'CURRENCYDATA_GETCURRENCYDATABYID_SUCCESS';
export const GETCURRENCYDATABYID_FAILURE = 'CURRENCYDATA_GETCURRENCYDATABYID_FAILURE';

export const GETALLCURRENCIES_REQUEST = 'ALLCURRENCIES_GETALLCURRENCIES_REQUEST';
export const GETALLCURRENCIES_SUCCESS = 'ALLCURRENCIES_GETALLCURRENCIES_SUCCESS';
export const GETALLCURRENCIES_FAILURE = 'ALLCURRENCIES_GETALLCURRENCIES_FAILURE';

export const GETTRENDINGCURRENCIES_REQUEST = 'TRENDINGCURRENCIES_GETTRENDINGCURRENCIES_REQUEST';
export const GETTRENDINGCURRENCIES_SUCCESS = 'TRENDINGCURRENCIES_GETTRENDINGCURRENCIES_SUCCESS';
export const GETTRENDINGCURRENCIES_FAILURE = 'TRENDINGCURRENCIES_GETTRENDINGCURRENCIES_FAILURE';

export const GETTOPCURRENCIES_REQUEST = 'TRENDINGCURRENCIES_GETTOPCURRENCIES_REQUEST';
export const GETTOPCURRENCIES_SUCCESS = 'TRENDINGCURRENCIES_GETTOPCURRENCIES_SUCCESS';
export const GETTOPCURRENCIES_FAILURE = 'TRENDINGCURRENCIES_GETTOPCURRENCIES_FAILURE';

export const GLOBALCURRENCYDATA_REQUEST = 'GLOBALCURRENCYDATA_GETGLOBALCURRENCYDATA_REQUEST';
export const GLOBALCURRENCYDATA_SUCCESS = 'GLOBALCURRENCYDATA_GETGLOBALCURRENCYDATA_SUCCESS';
export const GLOBALCURRENCYDATA_FAILURE = 'GLOBALCURRENCYDATA_GETGLOBALCURRENCYDATA_FAILURE';

export const GETMARKETCHARTDATA_REQUEST = 'MARKETCHARTDATA_GETMARKETCHARTDATADATA_REQUEST';
export const GETMARKETCHARTDATA_SUCCESS = 'MARKETCHARTDATA_GETMARKETCHARTDATADATA_SUCCESS';
export const GETMARKETCHARTDATA_FAILURE = 'MARKETCHARTDATA_GETMARKETCHARTDATADATA_FAILURE';

export const MAILINGLISTSUBSCRIBE_REQUEST = 'MAILINGLIST_MAILINGLISTSUBSCRIBE_REQUEST';
export const MAILINGLISTSUBSCRIBE_SUCCESS = 'MAILINGLIST_MAILINGLISTSUBSCRIBE_SUCCESS';
export const MAILINGLISTSUBSCRIBE_FAILURE = 'MAILINGLIST_MAILINGLISTSUBSCRIBE_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_SEARCH_FAILURE';

export const UPDATELOCALCURRENCY = 'LOCALCURRENCY_UPDATELOCALCURRENCY';

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
