// REDUX ACTION TYPES
export const GETCURRENCYTICKER_REQUEST = 'CURRENCYTICKER_GETCURRENCYTICKER_REQUEST';
export const GETCURRENCYTICKER_SUCCESS = 'CURRENCYTICKER_GETCURRENCYTICKER_SUCCESS';
export const GETCURRENCYTICKER_FAILURE = 'CURRENCYTICKER_GETCURRENCYTICKER_FAILURE';

export const GETTRENDINGCURRENCIES_REQUEST = 'TRENDINGCURRENCIES_GETTRENDINGCURRENCIES_REQUEST';
export const GETTRENDINGCURRENCIES_SUCCESS = 'TRENDINGCURRENCIES_GETTRENDINGCURRENCIES_SUCCESS';
export const GETTRENDINGCURRENCIES_FAILURE = 'TRENDINGCURRENCIES_GETTRENDINGCURRENCIES_FAILURE';

export const GLOBALCURRENCYDATA_REQUEST = 'GLOBALCURRENCYDATA_GETGLOBALCURRENCYDATA_REQUEST';
export const GLOBALCURRENCYDATA_SUCCESS = 'GLOBALCURRENCYDATA_GETGLOBALCURRENCYDATA_SUCCESS';
export const GLOBALCURRENCYDATA_FAILURE = 'GLOBALCURRENCYDATA_GETGLOBALCURRENCYDATA_FAILURE';
