const searchData = {
  data: {
    coins: [
      {
        id: 'bitcoin',
        name: 'Bitcoin',
        symbol: 'BTC',
        market_cap_rank: 1,
        thumb: 'https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png',
        large: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png',
      },
      {
        id: 'wrapped-bitcoin',
        name: 'Wrapped Bitcoin',
        symbol: 'WBTC',
        market_cap_rank: 13,
        thumb: 'https://assets.coingecko.com/coins/images/7598/thumb/wrapped_bitcoin_wbtc.png',
        large: 'https://assets.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png',
      },
      {
        id: 'bitcoin-cash',
        name: 'Bitcoin Cash',
        symbol: 'BCH',
        market_cap_rank: 24,
        thumb: 'https://assets.coingecko.com/coins/images/780/thumb/bitcoin-cash-circle.png',
        large: 'https://assets.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png',
      },
      {
        id: 'bittorrent',
        name: 'BitTorrent',
        symbol: 'BTT',
        market_cap_rank: 63,
        thumb: 'https://assets.coingecko.com/coins/images/22457/thumb/btt_logo.png',
        large: 'https://assets.coingecko.com/coins/images/22457/large/btt_logo.png',
      },
      {
        id: 'bitcoin-cash-sv',
        name: 'Bitcoin SV',
        symbol: 'BSV',
        market_cap_rank: 64,
        thumb: 'https://assets.coingecko.com/coins/images/6799/thumb/BSV.png',
        large: 'https://assets.coingecko.com/coins/images/6799/large/BSV.png',
      },
      {
        id: 'bitdao',
        name: 'BitDAO',
        symbol: 'BIT',
        market_cap_rank: 79,
        thumb: 'https://assets.coingecko.com/coins/images/17627/thumb/bitdao.jpg',
        large: 'https://assets.coingecko.com/coins/images/17627/large/bitdao.jpg',
      },
      {
        id: 'bitcoin-gold',
        name: 'Bitcoin Gold',
        symbol: 'BTG',
        market_cap_rank: 135,
        thumb: 'https://assets.coingecko.com/coins/images/1043/thumb/bitcoin-gold-logo.png',
        large: 'https://assets.coingecko.com/coins/images/1043/large/bitcoin-gold-logo.png',
      },
      {
        id: 'bitkub-coin',
        name: 'Bitkub Coin',
        symbol: 'KUB',
        market_cap_rank: 142,
        thumb: 'https://assets.coingecko.com/coins/images/15760/thumb/KUB.png',
        large: 'https://assets.coingecko.com/coins/images/15760/large/KUB.png',
      },
      {
        id: 'digitalbits',
        name: 'DigitalBits',
        symbol: 'XDB',
        market_cap_rank: 271,
        thumb: 'https://assets.coingecko.com/coins/images/8089/thumb/digitalbits-logo.jpg',
        large: 'https://assets.coingecko.com/coins/images/8089/large/digitalbits-logo.jpg',
      },
      {
        id: 'interest-bearing-bitcoin',
        name: 'Interest Bearing Bitcoin',
        symbol: 'IBBTC',
        market_cap_rank: 433,
        thumb: 'https://assets.coingecko.com/coins/images/15500/thumb/ibbtc.png',
        large: 'https://assets.coingecko.com/coins/images/15500/large/ibbtc.png',
      },
      {
        id: 'bitrue-token',
        name: 'Bitrue Coin',
        symbol: 'BTR',
        market_cap_rank: 452,
        thumb: 'https://assets.coingecko.com/coins/images/8873/thumb/Bittrue_logo.png',
        large: 'https://assets.coingecko.com/coins/images/8873/large/Bittrue_logo.png',
      },
      {
        id: 'bitcoin-diamond',
        name: 'Bitcoin Diamond',
        symbol: 'BCD',
        market_cap_rank: 545,
        thumb: 'https://assets.coingecko.com/coins/images/1254/thumb/bitcoin-diamond.png',
        large: 'https://assets.coingecko.com/coins/images/1254/large/bitcoin-diamond.png',
      },
      {
        id: 'bitmart-token',
        name: 'BitMart Token',
        symbol: 'BMX',
        market_cap_rank: 555,
        thumb: 'https://assets.coingecko.com/coins/images/5236/thumb/bitmart-token.png',
        large: 'https://assets.coingecko.com/coins/images/5236/large/bitmart-token.png',
      },
      {
        id: 'bitshares',
        name: 'BitShares',
        symbol: 'BTS',
        market_cap_rank: 559,
        thumb: 'https://assets.coingecko.com/coins/images/95/thumb/bitshares.png',
        large: 'https://assets.coingecko.com/coins/images/95/large/bitshares.png',
      },
      {
        id: 'hotbit-token',
        name: 'Hotbit Token',
        symbol: 'HTB',
        market_cap_rank: 679,
        thumb: 'https://assets.coingecko.com/coins/images/5990/thumb/hotbit-token.png',
        large: 'https://assets.coingecko.com/coins/images/5990/large/hotbit-token.png',
      },
      {
        id: 'new-bitshares',
        name: 'New BitShares',
        symbol: 'NBS',
        market_cap_rank: 808,
        thumb: 'https://assets.coingecko.com/coins/images/12532/thumb/Screenshot_2.png',
        large: 'https://assets.coingecko.com/coins/images/12532/large/Screenshot_2.png',
      },
      {
        id: 'bitcoin-2',
        name: 'Bitcoin 2',
        symbol: 'BTC2',
        market_cap_rank: 946,
        thumb: 'https://assets.coingecko.com/coins/images/5925/thumb/bitcoin2_logo256.png',
        large: 'https://assets.coingecko.com/coins/images/5925/large/bitcoin2_logo256.png',
      },
      {
        id: 'bitnautic',
        name: 'BitNautic',
        symbol: 'BTNT',
        market_cap_rank: 957,
        thumb: 'https://assets.coingecko.com/coins/images/2875/thumb/Logobit.jpg',
        large: 'https://assets.coingecko.com/coins/images/2875/large/Logobit.jpg',
      },
      {
        id: 'bitcoinstaking',
        name: 'BitcoinStaking',
        symbol: 'BSK',
        market_cap_rank: 1013,
        thumb: 'https://assets.coingecko.com/coins/images/12978/thumb/bsk.png',
        large: 'https://assets.coingecko.com/coins/images/12978/large/bsk.png',
      },
      {
        id: 'kan',
        name: 'BitKan',
        symbol: 'KAN',
        market_cap_rank: 1045,
        thumb: 'https://assets.coingecko.com/coins/images/4651/thumb/kan-token.png',
        large: 'https://assets.coingecko.com/coins/images/4651/large/kan-token.png',
      },
      {
        id: 'bitcny',
        name: 'bitCNY',
        symbol: 'BITCNY',
        market_cap_rank: 1087,
        thumb: 'https://assets.coingecko.com/coins/images/673/thumb/bitcny.png',
        large: 'https://assets.coingecko.com/coins/images/673/large/bitcny.png',
      },
      {
        id: 'probit-exchange',
        name: 'Probit Token',
        symbol: 'PROB',
        market_cap_rank: 1120,
        thumb: 'https://assets.coingecko.com/coins/images/6765/thumb/ProBit-Exchange-logo.png',
        large: 'https://assets.coingecko.com/coins/images/6765/large/ProBit-Exchange-logo.png',
      },
      {
        id: 'bitcoin-pro',
        name: 'Bitcoin Pro',
        symbol: 'BTCP',
        market_cap_rank: 1218,
        thumb: 'https://assets.coingecko.com/coins/images/3545/thumb/DSiD9ZhWsAE_8cS.png',
        large: 'https://assets.coingecko.com/coins/images/3545/large/DSiD9ZhWsAE_8cS.png',
      },
      {
        id: 'oxbitcoin',
        name: '0xBitcoin',
        symbol: '0XBTC',
        market_cap_rank: 1428,
        thumb: 'https://assets.coingecko.com/coins/images/4454/thumb/0xbtc.png',
        large: 'https://assets.coingecko.com/coins/images/4454/large/0xbtc.png',
      },
      {
        id: 'biconomy-exchange-token',
        name: 'Biconomy Exchange',
        symbol: 'BIT',
        market_cap_rank: 1466,
        thumb: 'https://assets.coingecko.com/coins/images/18198/thumb/mGky0OOh_400x400.jpg',
        large: 'https://assets.coingecko.com/coins/images/18198/large/mGky0OOh_400x400.jpg',
      },
    ],
    exchanges: [
      {
        id: 'whitebit',
        name: 'WhiteBIT',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/418/thumb/wb_3_avatar-02.png',
        large: 'https://assets.coingecko.com/markets/images/418/large/wb_3_avatar-02.png',
      },
      {
        id: 'bitmart',
        name: 'BitMart',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/239/thumb/Bitmart.png',
        large: 'https://assets.coingecko.com/markets/images/239/large/Bitmart.png',
      },
      {
        id: 'bitrue',
        name: 'Bitrue',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/254/thumb/Bitrue_Exchange.png',
        large: 'https://assets.coingecko.com/markets/images/254/large/Bitrue_Exchange.png',
      },
      {
        id: 'upbit',
        name: 'Upbit',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/117/thumb/upbit.png',
        large: 'https://assets.coingecko.com/markets/images/117/large/upbit.png',
      },
      {
        id: 'coinsbit',
        name: 'Coinsbit',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/267/thumb/Coinsbit.png',
        large: 'https://assets.coingecko.com/markets/images/267/large/Coinsbit.png',
      },
      {
        id: 'bitforex',
        name: 'Bitforex',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/214/thumb/BitForex-Logo.png',
        large: 'https://assets.coingecko.com/markets/images/214/large/BitForex-Logo.png',
      },
      {
        id: 'bitonbay',
        name: 'BitOnBay',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/280/thumb/bitonbay-exchange.png',
        large: 'https://assets.coingecko.com/markets/images/280/large/bitonbay-exchange.png',
      },
      {
        id: 'bithumb',
        name: 'Bithumb',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/6/thumb/bithumb_BI.png',
        large: 'https://assets.coingecko.com/markets/images/6/large/bithumb_BI.png',
      },
      {
        id: 'bitfinex',
        name: 'Bitfinex',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/4/thumb/BItfinex.png',
        large: 'https://assets.coingecko.com/markets/images/4/large/BItfinex.png',
      },
      {
        id: 'bybit_spot',
        name: 'Bybit (Spot)',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/698/thumb/bybit_spot.png',
        large: 'https://assets.coingecko.com/markets/images/698/large/bybit_spot.png',
      },
      {
        id: 'bitget',
        name: 'Bitget',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/540/thumb/Bitget_new_logo_2.png',
        large: 'https://assets.coingecko.com/markets/images/540/large/Bitget_new_logo_2.png',
      },
      {
        id: 'hotbit',
        name: 'Hotbit',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/201/thumb/hotbit.jpg',
        large: 'https://assets.coingecko.com/markets/images/201/large/hotbit.jpg',
      },
      {
        id: 'bitstamp',
        name: 'Bitstamp',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/9/thumb/bitstamp.jpg',
        large: 'https://assets.coingecko.com/markets/images/9/large/bitstamp.jpg',
      },
      {
        id: 'abit',
        name: 'Abit',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/623/thumb/ABIT.jpg',
        large: 'https://assets.coingecko.com/markets/images/623/large/ABIT.jpg',
      },
      {
        id: 'bitoffer',
        name: 'Bitoffer',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/456/thumb/S1naTFE.png',
        large: 'https://assets.coingecko.com/markets/images/456/large/S1naTFE.png',
      },
      {
        id: 'azbit',
        name: 'Azbit',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/787/thumb/azbit.jpeg',
        large: 'https://assets.coingecko.com/markets/images/787/large/azbit.jpeg',
      },
      {
        id: 'yobit',
        name: 'YoBit',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/46/thumb/yobit.png',
        large: 'https://assets.coingecko.com/markets/images/46/large/yobit.png',
      },
      {
        id: 'bitflyer',
        name: 'bitFlyer',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/5/thumb/bitFlyer-logo.png',
        large: 'https://assets.coingecko.com/markets/images/5/large/bitFlyer-logo.png',
      },
      {
        id: 'probit',
        name: 'ProBit Global',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/370/thumb/probit.png',
        large: 'https://assets.coingecko.com/markets/images/370/large/probit.png',
      },
      {
        id: 'bitbox',
        name: 'BITFRONT',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/245/thumb/bitfront.jpg',
        large: 'https://assets.coingecko.com/markets/images/245/large/bitfront.jpg',
      },
      {
        id: 'bitsoda',
        name: 'Bitsoda',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/476/thumb/DMRkY0iq_400x400.jpg',
        large: 'https://assets.coingecko.com/markets/images/476/large/DMRkY0iq_400x400.jpg',
      },
      {
        id: 'bithumb_global',
        name: 'BitGlobal',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/405/thumb/bitgloball.png',
        large: 'https://assets.coingecko.com/markets/images/405/large/bitgloball.png',
      },
      {
        id: 'bitmax',
        name: 'AscendEX (BitMax)',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/277/thumb/%E5%8E%9F%E8%89%B2.png',
        large: 'https://assets.coingecko.com/markets/images/277/large/%E5%8E%9F%E8%89%B2.png',
      },
      {
        id: 'bitvavo',
        name: 'Bitvavo',
        market_type: 'spot',
        thumb:
          'https://assets.coingecko.com/markets/images/714/thumb/bitvavo-mark-square-black.png',
        large:
          'https://assets.coingecko.com/markets/images/714/large/bitvavo-mark-square-black.png',
      },
      {
        id: 'bitkub',
        name: 'Bitkub',
        market_type: 'spot',
        thumb: 'https://assets.coingecko.com/markets/images/249/thumb/bitkub.png',
        large: 'https://assets.coingecko.com/markets/images/249/large/bitkub.png',
      },
    ],
    icos: [],
    categories: [
      {
        id: 1,
        name: 'Artificial Intelligence',
      },
      {
        id: 2,
        name: 'Augmented Reality',
      },
      {
        id: 3,
        name: 'Finance / Banking',
      },
      {
        id: 4,
        name: 'Big Data',
      },
      {
        id: 5,
        name: 'Business Services',
      },
      {
        id: 6,
        name: 'Charity',
      },
      {
        id: 7,
        name: 'Communication',
      },
      {
        id: 8,
        name: 'Cryptocurrency',
      },
      {
        id: 130,
        name: 'IoTeX Ecosystem',
      },
      {
        id: 10,
        name: 'Education',
      },
      {
        id: 11,
        name: 'Technology & Science',
      },
      {
        id: 12,
        name: 'Energy',
      },
      {
        id: 13,
        name: 'Entertainment',
      },
      {
        id: 14,
        name: 'Gambling',
      },
      {
        id: 15,
        name: 'Gig Economy',
      },
      {
        id: 16,
        name: 'Healthcare',
      },
      {
        id: 17,
        name: 'Infrastructure',
      },
      {
        id: 131,
        name: 'KardiaChain Ecosystem',
      },
      {
        id: 19,
        name: 'Investment',
      },
      {
        id: 20,
        name: 'Legal',
      },
      {
        id: 21,
        name: 'Manufacturing',
      },
      {
        id: 22,
        name: 'Media',
      },
      {
        id: 148,
        name: 'Elrond Ecosystem',
      },
      {
        id: 135,
        name: 'Ohm Fork',
      },
      {
        id: 25,
        name: 'Business Platform',
      },
      {
        id: 26,
        name: 'Protocol',
      },
      {
        id: 27,
        name: 'Real Estate',
      },
      {
        id: 28,
        name: 'Retail',
      },
      {
        id: 129,
        name: 'Tokenized Stock',
      },
      {
        id: 30,
        name: 'Software',
      },
      {
        id: 41,
        name: 'Masternodes',
      },
      {
        id: 128,
        name: 'Zilliqa Ecosystem',
      },
      {
        id: 33,
        name: 'Virtual Reality',
      },
      {
        id: 35,
        name: 'Asset-backed Tokens',
      },
      {
        id: 36,
        name: 'Stablecoins',
      },
      {
        id: 40,
        name: 'Index',
      },
      {
        id: 42,
        name: 'Remittance',
      },
      {
        id: 43,
        name: 'Social Money',
      },
      {
        id: 44,
        name: 'TokenSets',
      },
      {
        id: 46,
        name: 'Marketing',
      },
      {
        id: 47,
        name: 'ETF',
      },
      {
        id: 48,
        name: 'Reddit Points',
      },
      {
        id: 49,
        name: 'Tokenized Products',
      },
      {
        id: 50,
        name: 'CNY Stablecoin',
      },
      {
        id: 51,
        name: 'USD Stablecoin',
      },
      {
        id: 52,
        name: 'EUR Stablecoin',
      },
      {
        id: 53,
        name: 'GBP Stablecoin',
      },
      {
        id: 54,
        name: 'Tokenized BTC',
      },
      {
        id: 55,
        name: 'Compound Tokens',
      },
      {
        id: 56,
        name: 'Aave Tokens',
      },
      {
        id: 58,
        name: 'Synths',
      },
      {
        id: 59,
        name: 'Niftex Shards',
      },
      {
        id: 84,
        name: 'Eth 2.0 Staking',
      },
      {
        id: 64,
        name: 'Tokenized Gold',
      },
      {
        id: 68,
        name: 'LP Tokens',
      },
      {
        id: 72,
        name: 'Binance Launchpool',
      },
      {
        id: 73,
        name: 'DeFi Index',
      },
      {
        id: 74,
        name: 'US Election 2020',
      },
      {
        id: 75,
        name: 'Insurance',
      },
      {
        id: 76,
        name: 'Axie Infinity',
      },
      {
        id: 78,
        name: 'Fan Token',
      },
      {
        id: 81,
        name: 'Seigniorage',
      },
      {
        id: 83,
        name: 'Options',
      },
      {
        id: 86,
        name: 'Mirrored Assets',
      },
      {
        id: 87,
        name: 'KRW Stablecoin',
      },
      {
        id: 90,
        name: 'Prediction Markets',
      },
      {
        id: 92,
        name: 'Perpetuals',
      },
      {
        id: 94,
        name: 'Asset Manager',
      },
      {
        id: 95,
        name: 'HECO Chain Ecosystem',
      },
      {
        id: 96,
        name: 'Synthetic Issuer',
      },
      {
        id: 98,
        name: 'Layer 1',
      },
      {
        id: 100,
        name: 'NFT Index',
      },
      {
        id: 105,
        name: 'Number',
      },
      {
        id: 106,
        name: 'Collectibles',
      },
      {
        id: 107,
        name: 'Launchpad',
      },
      {
        id: 108,
        name: 'Wallets',
      },
      {
        id: 93,
        name: 'Centralized Exchange Token (CEX)',
      },
      {
        id: 111,
        name: 'uTokens',
      },
      {
        id: 126,
        name: 'Fractionalized NFT',
      },
      {
        id: 113,
        name: 'Meme Tokens',
      },
      {
        id: 114,
        name: 'DaoMaker Ecosystem',
      },
      {
        id: 110,
        name: 'Polygon Ecosystem',
      },
      {
        id: 116,
        name: 'MEV Protection',
      },
      {
        id: 117,
        name: 'RealT Tokens',
      },
      {
        id: 118,
        name: 'Leveraged Token',
      },
      {
        id: 132,
        name: 'Cardano Ecosystem',
      },
      {
        id: 136,
        name: 'Moonriver Ecosystem',
      },
      {
        id: 115,
        name: 'Gnosis Chain Ecosystem',
      },
      {
        id: 122,
        name: 'Arbitrum Ecosystem',
      },
      {
        id: 123,
        name: 'Celo Ecosystem',
      },
      {
        id: 139,
        name: 'Moonbeam Ecosystem',
      },
      {
        id: 125,
        name: 'Structured Products',
      },
      {
        id: 140,
        name: 'Wormhole Assets',
      },
      {
        id: 138,
        name: 'OEC Ecosystem',
      },
      {
        id: 97,
        name: 'Solana Ecosystem',
      },
      {
        id: 141,
        name: 'Farming-as-a-Service (FaaS)',
      },
      {
        id: 143,
        name: 'Liquid Staking Tokens',
      },
      {
        id: 63,
        name: 'Polkadot Ecosystem',
      },
      {
        id: 32,
        name: 'Tourism',
      },
      {
        id: 99,
        name: 'Avalanche Ecosystem',
      },
      {
        id: 109,
        name: 'Terra Ecosystem',
      },
      {
        id: 127,
        name: 'Impossible Launchpad',
      },
      {
        id: 39,
        name: 'Exchange-based Tokens',
      },
      {
        id: 71,
        name: 'BNB Chain Ecosystem',
      },
      {
        id: 29,
        name: 'Smart Contract Platform',
      },
      {
        id: 57,
        name: 'Governance',
      },
      {
        id: 142,
        name: 'cToken',
      },
      {
        id: 144,
        name: 'Edgeware Ecosystem',
      },
      {
        id: 145,
        name: 'Move To Earn',
      },
      {
        id: 147,
        name: 'Gotchiverse',
      },
      {
        id: 23,
        name: 'Music',
      },
      {
        id: 146,
        name: 'Ethereum Ecosystem',
      },
      {
        id: 45,
        name: 'Decentralized Finance (DeFi)',
      },
      {
        id: 85,
        name: 'Cosmos Ecosystem',
      },
      {
        id: 79,
        name: 'Yearn Ecosystem',
      },
      {
        id: 34,
        name: 'Storage',
      },
      {
        id: 77,
        name: 'Yield Aggregator',
      },
      {
        id: 121,
        name: 'Harmony Ecosystem',
      },
      {
        id: 69,
        name: 'Non-Fungible Tokens (NFT)',
      },
      {
        id: 65,
        name: 'Yield Farming',
      },
      {
        id: 9,
        name: 'Decentralized Exchange Token (DEX)',
      },
      {
        id: 112,
        name: 'Near Protocol Ecosystem',
      },
      {
        id: 70,
        name: 'Automated Market Maker (AMM)',
      },
      {
        id: 120,
        name: 'Fantom Ecosystem',
      },
      {
        id: 124,
        name: 'Olympus Pro',
      },
      {
        id: 31,
        name: 'Sports',
      },
      {
        id: 82,
        name: 'Derivatives',
      },
      {
        id: 62,
        name: 'Analytics',
      },
      {
        id: 91,
        name: 'Lending/Borrowing',
      },
      {
        id: 37,
        name: 'Privacy Coins',
      },
      {
        id: 60,
        name: 'Oracle',
      },
      {
        id: 89,
        name: 'Wrapped-Tokens',
      },
      {
        id: 18,
        name: 'Internet of Things (IOT)',
      },
      {
        id: 61,
        name: 'GameFi',
      },
      {
        id: 133,
        name: 'Guild and Scholarship',
      },
      {
        id: 88,
        name: 'Metaverse',
      },
      {
        id: 119,
        name: 'Play To Earn',
      },
      {
        id: 67,
        name: 'Rebase Tokens',
      },
    ],
    nfts: [
      {
        id: 'gh0stly-gh0sts',
        name: 'Gh0stly Gh0sts',
        symbol: 'GG',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/313/thumb/gh0stly-gh0sts.jpg',
      },
      {
        id: 'decentral-games-ice',
        name: 'Decentral Games ICE Poker',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/255/thumb/dg-games-ice.png',
      },
      {
        id: 'treeverse-plots',
        name: 'Treeverse Plots',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/266/thumb/treeverse-plots.png',
      },
      {
        id: null,
        name: 'SuperRare (v1)',
        symbol: 'SUPR',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Foundation',
        symbol: 'FND',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'The Proof of Attendance Protocol',
        symbol: 'POAP',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Rarible',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'OpenSea',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Charged Particles',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Chain/Saw',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'BitWine',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'SuperRare',
        symbol: 'SUPR',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Async Art',
        symbol: 'ASYNC',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'MakersPlace',
        symbol: 'MKT',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'KnownOrigin',
        symbol: 'KODA',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'pudgy-presents',
        name: 'Pudgy Presents',
        symbol: 'PP',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/319/thumb/pudgy-presents.gif',
      },
      {
        id: null,
        name: 'CryptoKitties',
        symbol: 'CK',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Zora',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Meme Ltd.',
        symbol: 'MEME',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Axie Infinity',
        symbol: 'AXIE',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'pixelmon',
        name: 'Pixelmon',
        symbol: 'PXLMN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/279/thumb/pixelmon.gif',
      },
      {
        id: null,
        name: 'Robert Alice iNFT',
        symbol: 'RALICE.INFT',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'FISHΞRMAN Packs by Steven Baltay',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'clonex',
        name: 'CloneX',
        symbol: 'CLONEX',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/265/thumb/clonex.png',
      },
      {
        id: null,
        name: 'DeadHeads',
        symbol: 'DEAD',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Art Blocks',
        symbol: 'BLOCKS',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'FameLadySquad',
        symbol: 'FLS',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Untamed Elephants',
        symbol: 'UE',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Monas',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Barn Owlz',
        symbol: 'OWLZ',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Gutter Rats',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Furry Faced Fellas',
        symbol: 'FFF',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'The Doge Pound',
        symbol: 'DOGGY',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'the-seekers',
        name: 'The Seekers',
        symbol: 'SEEKERS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/301/thumb/the-seekers.png',
      },
      {
        id: null,
        name: 'Avid Lines',
        symbol: 'ALIN',
        thumb: 'missing_thumb.png',
      },
      {
        id: null,
        name: 'Crypto Cannabis Club',
        symbol: 'CCC',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'ens-ethereum-name-service',
        name: 'ENS: Ethereum Name Service',
        symbol: 'ENS',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/373/thumb/ens-ethereum-name-service.png',
      },
      {
        id: 'apes-of-space',
        name: 'Apes of Space',
        symbol: 'AOS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/119/thumb/AOS.jpg',
      },
      {
        id: 'milady-maker',
        name: 'Milady Maker',
        symbol: 'MIL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/317/thumb/milady-maker.png',
      },
      {
        id: 'cyberbrokers-v3',
        name: 'CyberBrokers',
        symbol: 'CYBERBROKERS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/280/thumb/cyberbrokers-v3.png',
      },
      {
        id: 'alpha-kongs-club-akc',
        name: 'Alpha Kongs Club - AKC',
        symbol: 'AKC',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/334/thumb/alpha-kongs-club-akc.png',
      },
      {
        id: 'derpy-birbs',
        name: 'Derpy Birbs',
        symbol: 'DERPYBIRBS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/43/thumb/derpy.png',
      },
      {
        id: 'compass-lifetime-pass',
        name: 'Compass Lifetime Pass',
        symbol: 'CLP',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/359/thumb/compass-lifetime-pass.png',
      },
      {
        id: '',
        name: 'SupDucks',
        symbol: 'SD',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'gods-unchained',
        name: 'Gods Unchained',
        symbol: 'GODS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/10/thumb/gods_unchained.png',
      },
      {
        id: 'non-fungible-soup',
        name: 'Non-Fungible Soup',
        symbol: 'NFS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/185/thumb/unnamed.png',
      },
      {
        id: 'the-association',
        name: 'The Association',
        symbol: 'ASSOC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/362/thumb/the-association.jpg',
      },
      {
        id: 'bloot',
        name: 'Bloot',
        symbol: 'BLOOT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/120/thumb/BLOOT.png',
      },
      {
        id: 'moar-by-joan-cornella',
        name: '"MOAR" by Joan Cornella',
        symbol: 'MOAR',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/335/thumb/moar-by-joan-cornella.png',
      },
      {
        id: 'warkittens-genesis',
        name: 'WarKittens Genesis',
        symbol: 'KITTEN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/354/thumb/warkittens-genesis.png',
      },
      {
        id: 'bff-friendship-bracelets',
        name: 'BFF Friendship Bracelets',
        symbol: '✺BFF',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/367/thumb/bff-friendship-bracelets.gif',
      },
      {
        id: 'nft-worlds',
        name: 'NFT Worlds',
        symbol: 'NFT WORLDS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/282/thumb/nft-worlds.gif',
      },
      {
        id: 'hape-prime',
        name: 'Hape Prime',
        symbol: 'HAPE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/284/thumb/hapeprime.png',
      },
      {
        id: 'beanz-official',
        name: 'BEANZ Official',
        symbol: 'SMTH',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/292/thumb/beanz-official.jpg',
      },
      {
        id: 'mems-voyage-one',
        name: 'Mems, Voyage One',
        symbol: 'MEMS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/357/thumb/mems-voyage-one.png',
      },
      {
        id: 'arcade-land',
        name: 'Arcade Land',
        symbol: 'ARCLAND',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/296/thumb/arcade-land.jpg',
      },
      {
        id: 'tubby-cats',
        name: 'Tubby Cats',
        symbol: 'TUBBY',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/276/thumb/tubby-cats.png',
      },
      {
        id: 'world-of-women',
        name: 'World of Women',
        symbol: 'WOW',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/49/thumb/world-of-women.png',
      },
      {
        id: 'feline-fiendz-nft',
        name: 'Feline Fiendz NFT',
        symbol: 'FF',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/331/thumb/feline-fiendz-nft.png',
      },
      {
        id: 'sipherian-inu',
        name: 'Sipherian Inu',
        symbol: 'INU',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/136/thumb/SIPHER.jpg',
      },
      {
        id: 'the-doge-pound',
        name: 'The Doge Pound',
        symbol: 'DOGGY',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/111/thumb/doge_pound.jpg',
      },
      {
        id: 'embersword-badge',
        name: '',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/323/thumb/ember.jpeg',
      },
      {
        id: 'crypto-raiders-mounts',
        name: 'Crypto Raiders Mounts',
        symbol: 'CRMOUNT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/339/thumb/unnamed.png',
      },
      {
        id: 'stoner-cats',
        name: 'Stoner Cats',
        symbol: 'TOKEN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/235/thumb/unnamed.png',
      },
      {
        id: 'dezuki',
        name: 'DEZUKI',
        symbol: 'DEZUKI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/327/thumb/dezuki.gif',
      },
      {
        id: 'premint-collector-pass-official',
        name: 'PREMINT Collector Pass - OFFICIAL',
        symbol: 'PREMINTCOLL',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/364/thumb/premint-collector-pass-official.png',
      },
      {
        id: 'ash-chapter-two-metamorphosis',
        name: 'Ash Chapter Two: Metamorphosis',
        symbol: 'MORPH',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/321/thumb/ash-chapter-two-metamorphosis.gif',
      },
      {
        id: 'satoshibles',
        name: 'Satoshibles',
        symbol: 'SBLS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/218/thumb/8bhz_WdL_400x400.jpeg',
      },
      {
        id: 'toons-official',
        name: 'Toons Official',
        symbol: 'TOONS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/356/thumb/toons-official.png',
      },
      {
        id: 'capsule-house',
        name: 'Capsule House',
        symbol: 'CAPSULE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/158/thumb/Capsule.jpg',
      },
      {
        id: '8bit',
        name: '8 Bit Universe',
        symbol: '8BIT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/94/thumb/8BIT.jpg',
      },
      {
        id: 'gensis-mana',
        name: 'Genesis Mana',
        symbol: 'GMANA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/163/thumb/GMANA.png',
      },
      {
        id: 'bored-ape-kennel-club',
        name: 'Bored Ape Kennel Club',
        symbol: 'BAKC',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/233/thumb/bored-ape-kennel-club.png',
      },
      {
        id: 'pxn-ghost-divison',
        name: 'PXN: Ghost Divison',
        symbol: 'GHOST',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/368/thumb/pxn-ghost-divison.jpg',
      },
      {
        id: 'adam-bomb-squad',
        name: 'Adam Bomb Squad',
        symbol: 'ABS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/113/thumb/ADAM.jpg',
      },
      {
        id: '8SIAN',
        name: '8SIAN',
        symbol: '8SIAN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/247/thumb/8sian.png',
      },
      {
        id: 'star-sailor-siblings',
        name: 'Star Sailor Sibings',
        symbol: 'SSS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/64/thumb/SSS.png',
      },
      {
        id: 'cypher',
        name: 'Cypher',
        symbol: 'CPHR',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/67/thumb/Cypher.jpg',
      },
      {
        id: 'doodles-official',
        name: 'Doodles',
        symbol: 'DOODLE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/242/thumb/3R7s-ZV0_400x400.jpg',
      },
      {
        id: 'you-by-bff',
        name: 'You by BFF',
        symbol: '✺YOU',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/361/thumb/you-by-bff.jpg',
      },
      {
        id: 'bored-ape-chemistry-club',
        name: 'Bored Ape Chemistry Club',
        symbol: '',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/299/thumb/bored-ape-chemistry-club.jpg',
      },
      {
        id: 'murder-head-death-club',
        name: 'Murder Head Death Club',
        symbol: 'MHDC',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/348/thumb/murder-head-death-club.jpg',
      },
      {
        id: 'vaynersports-pass-vsp',
        name: 'VaynerSports Pass VSP',
        symbol: 'VSP',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/325/thumb/vaynersports-pass-vsp.png',
      },
      {
        id: 'peopleintheplacetheylove',
        name: 'PeopleInThePlaceTheyLove',
        symbol: 'PPTL',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/309/thumb/peopleintheplacetheylove.png',
      },
      {
        id: 'lilpudgys',
        name: 'Lil Pudgys',
        symbol: 'LILPUDGYS',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'max-pain-and-frens-by-xcopy',
        name: 'MAX PAIN AND FRENS BY XCOPY',
        symbol: 'MAXPAINANDFRENSOPENEDITIONBYXCOPY',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/302/thumb/max-pain-and-frens-by-xcopy.png',
      },
      {
        id: 'antebellum-genesis-land',
        name: 'Antebellum Genesis Land',
        symbol: 'LOV',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/343/thumb/antebellum-genesis-land.jpg',
      },
      {
        id: 'official-kreepy-club',
        name: 'OFFICIAL KREEPY CLUB',
        symbol: 'KREEPS',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/347/thumb/official-kreepy-club.jpg',
      },
      {
        id: 'etherlambos',
        name: 'EtherLambos',
        symbol: 'EL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/114/thumb/Etherlambos.jpg',
      },
      {
        id: 'cryptophunks',
        name: 'CryptoPhunks',
        symbol: 'PHUNK',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/374/thumb/cryptophunks.png',
      },
      {
        id: 'los-muertos-world',
        name: 'Los Muertos World',
        symbol: 'LOSMUERTOS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/341/thumb/los-muertos-world.gif',
      },
      {
        id: 'women-of-aradena',
        name: 'Women of Aradena',
        symbol: 'WOA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/306/thumb/_JzAyLOb_400x400.jpeg',
      },
      {
        id: 'unemployables',
        name: 'Unemployables',
        symbol: 'UNE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/351/thumb/unemployables.jpg',
      },
      {
        id: 'deadfellaz',
        name: 'DeadFellaz',
        symbol: 'DEADFELLAZ',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/360/thumb/deadfellaz.png',
      },
      {
        id: 'glue-factory-show',
        name: 'Glue Factory Show',
        symbol: 'GFS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/70/thumb/Glue_Factoryu.png',
      },
      {
        id: 'bapetaverse',
        name: '(B)APETAVERSE',
        symbol: 'BVS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/290/thumb/bapetaverse.jpeg',
      },
      {
        id: 'asm-brains',
        name: 'ASM Brains',
        symbol: 'ASMBRAIN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/371/thumb/asm-brains.png',
      },
      {
        id: 'cupcat-nft',
        name: 'Cupcat NFT',
        symbol: 'CUPCAT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/272/thumb/9jm1B2SJ_400x400.jpeg',
      },
      {
        id: 'akutars',
        name: 'Akutars',
        symbol: 'AKU',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/363/thumb/akutars.png',
      },
      {
        id: 'squarmies',
        name: 'Squarmies',
        symbol: 'SQUARES',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/273/thumb/pnxZX6rm_400x400.png',
      },
      {
        id: 'rebelbots',
        name: 'RebelBots',
        symbol: 'RB',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/285/thumb/v9dTwhGw_400x400.png',
      },
      {
        id: 'template',
        name: 'Template',
        symbol: 'TMPLT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/81/thumb/TEMPLATE.jpg',
      },
      {
        id: 'pepeverse',
        name: 'PEPEVERSE &#127760; &#128056;',
        symbol: 'PEPEVERSE &#127760; &#128056;',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'corruptedog',
        name: 'CorruptedOG',
        symbol: 'COGS',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'akuma-origins',
        name: 'Akuma Origins',
        symbol: 'AKUMA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/320/thumb/akuma-origins.jpg',
      },
      {
        id: 'murakami-flowers-seed',
        name: 'Murakami.Flowers Seed',
        symbol: 'SEED',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/315/thumb/murakami-flowers-seed.png',
      },
      {
        id: 'froyo-kittens',
        name: 'froyo kittens',
        symbol: 'FROYOKITTEN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/336/thumb/froyo-kittens.png',
      },
      {
        id: 'liquid-cacophony',
        name: 'Liquid Cacophony',
        symbol: 'LCNOBODY',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'bigcomic-paintings',
        name: 'BigComic Paintings',
        symbol: 'COMIC',
        thumb: 'missing_thumb.png',
      },
      {
        id: 're-digitalization-of-waves',
        name: 'Re-Digitalization of Waves',
        symbol: 'RDW',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'messari-2022-theses',
        name: 'Messari 2022 Theses ',
        symbol: 'MAT22',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/208/thumb/hSdtq7qu_400x400.jpg',
      },
      {
        id: 'where-did-macy-go',
        name: 'Where Did Macy Go?',
        symbol: 'MACY',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'mixed_feelings',
        name: 'MixedFeelings ',
        symbol: 'MIXED_FEELINGS',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'weather-report',
        name: 'Weather Report Intl.',
        symbol: 'WR',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/288/thumb/weather-report-intl.jpeg',
      },
      {
        id: 'ethermore',
        name: 'Ethermore',
        symbol: 'ETE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/137/thumb/Ethermore.png',
      },
      {
        id: 'fomoverse',
        name: 'Fomoverse',
        symbol: 'FOMO',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/159/thumb/FOMO.png',
      },
      {
        id: 'spirit-orb-pets ',
        name: 'Spirit Orb Pets',
        symbol: 'SOPV0',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/177/thumb/unnamed.png',
      },
      {
        id: 'starry-nift',
        name: 'StarryNift',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/171/thumb/logo_blackname1.png',
      },
      {
        id: 'ragnarok-meta',
        name: 'Ragnarok Meta',
        symbol: 'RONIN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/365/thumb/ragnarok-meta.gif',
      },
      {
        id: 'borpacasso',
        name: 'Borpacasso',
        symbol: 'BORP1',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/168/thumb/BORP.jpg',
      },
      {
        id: 'evaverse',
        name: 'Evaverse',
        symbol: 'EVA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/316/thumb/evaverse.jpg',
      },
      {
        id: 'passive-apes',
        name: 'Passive Apes',
        symbol: 'APES',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/40/thumb/passive_apes.png',
      },
      {
        id: 'asm-aifa-all-stars',
        name: 'ASM AIFA All-Stars',
        symbol: 'AIFACHARACTER',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/372/thumb/asm-aifa-all-stars.png',
      },
      {
        id: 'the-anata-nft',
        name: 'The Anata NFT',
        symbol: 'ANATA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/355/thumb/the-anata-nft.png',
      },
      {
        id: 'asm-aifa-genesis',
        name: 'ASM AIFA Genesis',
        symbol: 'AIFABOX',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/370/thumb/asm-aifa-genesis.png',
      },
      {
        id: 'hikari-official',
        name: 'Hikari Official',
        symbol: 'HIKARI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/353/thumb/hikari-official.jpg',
      },
      {
        id: 'zunks',
        name: 'Zunks',
        symbol: 'ZUNK',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/375/thumb/zunks.gif',
      },
      {
        id: 'squid-dao-nft',
        name: 'SquidDAONFT',
        symbol: 'SQDN',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'animetas',
        name: 'Animetas',
        symbol: 'ANMT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/44/thumb/animetas.png',
      },
      {
        id: 'evaverse-turtle-troop',
        name: 'Evaverse Turtle Troop',
        symbol: 'TRTL',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/314/thumb/evaverse-turtle-troop.gif',
      },
      {
        id: 'ape-dao-remix',
        name: 'APE DAO REMIX!',
        symbol: 'APEDREMIX',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/154/thumb/APE_DAO.jpg',
      },
      {
        id: 'mondriannft',
        name: 'MondrianNFT',
        symbol: 'MND',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/186/thumb/unnamed_%281%29.png',
      },
      {
        id: 'eva-hoverboard',
        name: 'Eva Hoverboard',
        symbol: 'HOVR',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/322/thumb/Evaverse.jpeg',
      },
      {
        id: 'cryptohoots-steampunk-parliament',
        name: 'CryptoHoots Steampunk Parliament',
        symbol: 'HOOTS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/160/thumb/CryptoHoots.jpg',
      },
      {
        id: 'avastars',
        name: 'Avastars',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/259/thumb/avastars.gif',
      },
      {
        id: 'haki-nft',
        name: 'HAKI NFT',
        symbol: 'HAKI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/344/thumb/haki-nft.gif',
      },
      {
        id: 'citizens-of-bulliever-island',
        name: 'Citizens of Bulliever Island',
        symbol: 'COBI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/77/thumb/COBI.jpg',
      },
      {
        id: 'repus',
        name: 'The Repus',
        symbol: 'REPUS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/275/thumb/the-repus-nft.gif',
      },
      {
        id: 'dope-shibas',
        name: 'Dope Shibas',
        symbol: 'DOPESHIBA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/93/thumb/unnamed.png',
      },
      {
        id: 'parallel',
        name: 'Parallel',
        symbol: 'LL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/35/thumb/Parallel.jpg',
      },
      {
        id: 'inbetweeners',
        name: 'inbetweeners',
        symbol: 'IBNS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/234/thumb/ibtw.png',
      },
      {
        id: 'shinsekai-portal',
        name: 'Shinsekai Portal',
        symbol: 'SSK',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/337/thumb/shinsekai-portal.png',
      },
      {
        id: 'world-of-women-galaxy',
        name: 'World of Women Galaxy',
        symbol: 'WOWG',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/291/thumb/wowg_1.png',
      },
      {
        id: 'lobsterdao',
        name: 'lobsterdao',
        symbol: 'LOBS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/287/thumb/lobsterdao.jpeg',
      },
      {
        id: 'zombieclub-token',
        name: 'ZombieClub Token',
        symbol: 'ZCT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/308/thumb/zombieclub-token.jpg',
      },
      {
        id: 'nightkids',
        name: 'Night Kids',
        symbol: 'NMS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/72/thumb/NK.png',
      },
      {
        id: 'mfers',
        name: 'mfers',
        symbol: 'MFER',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/312/thumb/mfers.png',
      },
      {
        id: 'metahero',
        name: 'MetaHero',
        symbol: 'HERO',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/132/thumb/HERO.jpg',
      },
      {
        id: 'mojimon',
        name: 'Mojimon',
        symbol: 'MOJI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/97/thumb/MOJI.jpg',
      },
      {
        id: 'fvck_avatar',
        name: 'FVCK_AVATAR//',
        symbol: 'FVCK_AVATAR//',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/332/thumb/fvck_avatar.jpg',
      },
      {
        id: 'mooncats-acclimated',
        name: 'MoonCats - Acclimated',
        symbol: '😺',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/144/thumb/mooncats.png',
      },
      {
        id: 'town-star',
        name: 'Town Star',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/297/thumb/town-star.png',
      },
      {
        id: 'cryptozombiez',
        name: 'CryptoZombiez',
        symbol: 'ZOMBIE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/193/thumb/-GnUxUz1_400x400.png',
      },
      {
        id: 'alphasharks-nft',
        name: 'AlphaSharks NFT',
        symbol: 'ALPHASHARKS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/358/thumb/alphasharks-nft.gif',
      },
      {
        id: 'luchadores-io',
        name: 'Luchadores.io',
        symbol: 'LUCHADORES',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/345/thumb/luchadores-io.png',
      },
      {
        id: 'pudgy-halloween',
        name: 'Pudgy Halloween',
        symbol: '',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'ready-player-cat-nft',
        name: 'Ready Player Cat NFT',
        symbol: 'MAODAO-RPC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/69/thumb/Ready_Player_Cat.png',
      },
      {
        id: 'everai-heroes-duo',
        name: 'Everai Heroes: Duo',
        symbol: 'EVERAIDUO',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/294/thumb/everai-heroes-duo.gif',
      },
      {
        id: 'warriors-of-aradena',
        name: 'Warriors of Aradena',
        symbol: 'WOA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/305/thumb/_JzAyLOb_400x400.jpeg',
      },
      {
        id: 'metroverse',
        name: 'Metroverse',
        symbol: 'METROBLOCK',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/258/thumb/unnamed.png',
      },
      {
        id: 'settlements',
        name: 'Settlements',
        symbol: 'STL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/121/thumb/Settlements.jpg',
      },
      {
        id: 'united-punks-union',
        name: 'United Punks Union',
        symbol: 'UPU',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/244/thumb/unnamed.gif',
      },
      {
        id: 'generative-masks',
        name: 'Generative Masks',
        symbol: 'GM',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/46/thumb/generative-masks.png',
      },
      {
        id: 'cool-cats',
        name: 'Cool Cats',
        symbol: 'COOL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/48/thumb/coolcats.png',
      },
      {
        id: 'io-imaginary-ones',
        name: 'IO: Imaginary Ones',
        symbol: 'IO',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/377/thumb/io-imaginary-ones.jpg',
      },
      {
        id: 'loomlocknft',
        name: 'loomlock NFT',
        symbol: 'LL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/149/thumb/LL.jpg',
      },
      {
        id: 'xloot',
        name: 'Extension Loot (xLoot)',
        symbol: 'XLOOT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/118/thumb/xloot.png',
      },
      {
        id: 'otherdeed-for-otherside',
        name: 'Otherdeed for Otherside',
        symbol: 'OTHR',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/366/thumb/otherdeed-for-otherside.jpg',
      },
      {
        id: 'muri-haus',
        name: 'MURI by Haus',
        symbol: 'MURI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/289/thumb/muri-by-haus.png',
      },
      {
        id: 'sandbox',
        name: 'LAND',
        symbol: "SANDBOX'S LANDS",
        thumb: 'https://assets.coingecko.com/nft_contracts/images/188/thumb/sand.png',
      },
      {
        id: '3landers',
        name: '3Landers',
        symbol: '3L',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/277/thumb/3landers.gif',
      },
      {
        id: 'shinsei-galverse-official',
        name: 'Shinsei Galverse Official',
        symbol: 'GALS',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/350/thumb/shinsei-galverse-official.png',
      },
      {
        id: 'spookies',
        name: 'Spookies',
        symbol: 'SPOOK',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/195/thumb/unnamed.jpg',
      },
      {
        id: 'lives-of-asuna',
        name: 'Lives of Asuna',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/267/thumb/lives-of-asuna.gif',
      },
      {
        id: 'fancy bears',
        name: 'Fancy Bears',
        symbol: 'BEARS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/286/thumb/Bears.jpeg',
      },
      {
        id: 'fluf-world',
        name: 'FLUF World',
        symbol: 'FLUF',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/150/thumb/FLUF.png',
      },
      {
        id: 'punks-comic',
        name: 'PUNKS Comic',
        symbol: 'COMIC2',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/236/thumb/unnamed.jpeg',
      },
      {
        id: 'strange-attractors',
        name: 'Strange Attractors',
        symbol: 'SA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/184/thumb/FLovQrdw_400x400.jpg',
      },
      {
        id: 'embersword-land',
        name: 'Embersword Land',
        symbol: 'LAND',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/324/thumb/ember.jpeg',
      },
      {
        id: 'lee-mullican',
        name: 'Lee Mullican',
        symbol: 'MUL',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'notbanksyechoes',
        name: 'notBanksyEchoes',
        symbol: 'NB',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/346/thumb/notbanksyechoes.gif',
      },
      {
        id: 'global-citizen-club',
        name: 'Global Citizen Club',
        symbol: 'GCC',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/261/thumb/global-citizen-club.jpeg',
      },
      {
        id: 'bored-ape-yacht-club',
        name: 'Bored Ape Yacht Club',
        symbol: 'BAYC',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/20/thumb/bored-ape-yacht-club.png',
      },
      {
        id: 'covidpunks',
        name: 'COVIDPunks',
        symbol: 'PUNK-19',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/116/thumb/Covid.jpg',
      },
      {
        id: 'dooplicator',
        name: 'Dooplicator',
        symbol: 'DOOPL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/376/thumb/dooplicator.jpg',
      },
      {
        id: 'moonbirds',
        name: 'Moonbirds',
        symbol: 'MOONBIRD',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/349/thumb/moonbirds.png',
      },
      {
        id: 'revenants-by-alethea-ai',
        name: 'Revenants by Alethea AI',
        symbol: 'REV',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/164/thumb/revenants-alethea-ai.png',
      },
      {
        id: 'light-super-bunnies',
        name: 'Light Super Bunnies',
        symbol: 'LSB',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/99/thumb/LSB.jpg',
      },
      {
        id: 'karafuru',
        name: 'Karafuru',
        symbol: 'KARAFURU',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/283/thumb/karafuru.jpeg',
      },
      {
        id: 'singularity-by-aiiv',
        name: 'Singularity by AIIV',
        symbol: 'AIIVSINGULARITY',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/157/thumb/Singularity.png',
      },
      {
        id: 'zipcy-supernormal',
        name: "Zipcy's SuperNormal",
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/268/thumb/zipcy-supernormal.gif',
      },
      {
        id: 'veecon-tickets',
        name: 'VeeCon  Tickets',
        symbol: 'VC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/298/thumb/veecon-tickets.png',
      },
      {
        id: 'phantabear',
        name: 'Phanta Bear',
        symbol: 'PHB',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/237/thumb/phantabear.png',
      },
      {
        id: 'kiwami-genesis',
        name: 'KIWAMI Genesis',
        symbol: 'KIWAMI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/293/thumb/kiwami-genesis.png',
      },
      {
        id: 'the-mekabots',
        name: 'The Mekabots',
        symbol: 'MBOT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/310/thumb/the-mekabots.png',
      },
      {
        id: 'incrementum',
        name: 'Incrementum',
        symbol: 'INCRMNTM',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/101/thumb/INCRTM.jpg',
      },
      {
        id: 'fortune',
        name: 'Fortune',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/39/thumb/fortune.png',
      },
      {
        id: 'bored-bananas',
        name: 'Bored Bananas',
        symbol: 'BANANA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/180/thumb/unnamed.png',
      },
      {
        id: 'boss-beauties',
        name: 'Boss Beauties',
        symbol: 'BOSSB',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/263/thumb/bossbeauties.jpeg',
      },
      {
        id: 'cryptopunks',
        name: 'CryptoPunks',
        symbol: 'Ͼ',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/270/thumb/cryptopunks.png',
      },
      {
        id: 'genesisapostle',
        name: 'GenesisApostle',
        symbol: 'GENESISAPOSTLE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/183/thumb/unnamed.png',
      },
      {
        id: 'gauntlets',
        name: 'Gauntlets',
        symbol: 'GNT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/78/thumb/Gauntlets.png',
      },
      {
        id: 'impostors-genesis-aliens',
        name: 'Impostors Genesis Aliens',
        symbol: 'IMPOSTORS',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/295/thumb/impostors-genesis-aliens.gif',
      },
      {
        id: 'bobu-the-bean-farmer',
        name: 'Bobu, the Bean Farmer',
        symbol: '',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/318/thumb/bobu-the-bean-farmer.gif',
      },
      {
        id: 'the-vogu-collective',
        name: 'The Vogu Collective',
        symbol: 'VGT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/36/thumb/vogu.png',
      },
      {
        id: 'mutant-shiba-club-msc',
        name: 'Mutant Shiba Club | MSC',
        symbol: 'MSC',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/330/thumb/mutant-shiba-club-msc.gif',
      },
      {
        id: 'invisible-friends',
        name: 'Invisible Friends',
        symbol: 'INVSBLE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/281/thumb/invisible-friends.png',
      },
      {
        id: 'something-token',
        name: 'Something Token',
        symbol: 'SOMETHING',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/369/thumb/something-token.gif',
      },
      {
        id: 'proof-collective',
        name: 'PROOF Collective',
        symbol: 'PROOF',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/329/thumb/proof-collective.png',
      },
      {
        id: 'veefriends',
        name: 'VeeFriends',
        symbol: 'VFT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/257/thumb/veefriends.png',
      },
      {
        id: 'meebits',
        name: 'Meebits',
        symbol: '⚇',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/28/thumb/meebits.png',
      },
      {
        id: 'sneaky-vampire-syndicate',
        name: 'Sneaky Vampire Syndicate',
        symbol: 'SVS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/143/thumb/SVS.png',
      },
      {
        id: 'jrny-nft-club',
        name: 'JRNY NFT Club',
        symbol: 'JNC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/201/thumb/jrny.gif',
      },
      {
        id: 'coolpets',
        name: 'Cool Pets',
        symbol: 'PETS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/260/thumb/coolpets.png',
      },
      {
        id: 'crypto-raiders-mobs',
        name: 'Crypto Raiders MOBS',
        symbol: 'MOBSKEY',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/338/thumb/unnamed.png',
      },
      {
        id: 'chibi-dinos',
        name: 'CHIBI DINOS',
        symbol: 'CHIBIDINOS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/115/thumb/CHIBI.png',
      },
      {
        id: 'neo-tokyo-punks-nft',
        name: 'Neo Tokyo Punks NFT',
        symbol: 'NTP',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/333/thumb/neo-tokyo-punks-nft.gif',
      },
      {
        id: 'the-picaroons',
        name: 'The Picaroons',
        symbol: 'PIC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/352/thumb/the-picaroons.png',
      },
      {
        id: 'cryptocoven',
        name: 'Crypto Coven',
        symbol: 'WITCH',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/256/thumb/cryptocoven.png',
      },
      {
        id: '0n1force',
        name: '0N1 Force',
        symbol: '0N1',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/59/thumb/unnamed_%283%29.png',
      },
      {
        id: 'the-art-of-seasons',
        name: 'The Art of Seasons',
        symbol: 'TAOS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/342/thumb/the-art-of-seasons.gif',
      },
      {
        id: 'superlative-secret-society',
        name: 'The Superlative Secret Society',
        symbol: 'SUPERLATIVESS',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/274/thumb/superlative-secret-society.gif',
      },
      {
        id: 'cryptoadz',
        name: 'CrypToadz',
        symbol: 'TOADZ',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/146/thumb/TOADZ.jpg',
      },
      {
        id: 'friendsies',
        name: 'fRiENDSiES',
        symbol: 'FRIENDSIES',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/303/thumb/friendsies.jpg',
      },
      {
        id: 'ethereals-wtf',
        name: 'Ethereals WTF',
        symbol: 'BOOO',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/262/thumb/ethereals-wtf.png',
      },
      {
        id: 'blitmap',
        name: 'Blitmap',
        symbol: 'BLIT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/264/thumb/blitmap.gif',
      },
      {
        id: 'pudgy-penguins',
        name: 'PudgyPenguins',
        symbol: 'PPG',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/38/thumb/pudgypenguin.jpeg',
      },
      {
        id: 'byoland',
        name: 'BYO Land',
        symbol: 'BYOLAND',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/243/thumb/Screenshot_2022-01-10_182421.png',
      },
      {
        id: 'cryptodragons-eggs',
        name: 'CryptoDragons Eggs',
        symbol: 'CDE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/230/thumb/unnamed.png',
      },
      {
        id: 'ethlizards',
        name: 'Ethlizards',
        symbol: 'LIZARD',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/311/thumb/ethlizards.png',
      },
      {
        id: 'metroverse-blackout',
        name: 'Metroverse Blackout',
        symbol: 'METROBLOCK2',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/328/thumb/metroverse-blackout.png',
      },
      {
        id: 'aradena-comics',
        name: 'Aradena Comics',
        symbol: 'AC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/307/thumb/_JzAyLOb_400x400.jpeg',
      },
      {
        id: 'party-degenerates',
        name: 'PartyDegenerates',
        symbol: 'PARTY',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/175/thumb/9kvEG6KT_400x400.jpg',
      },
      {
        id: 'cyberkongz',
        name: 'CyberKongz',
        symbol: 'KONGZ',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/90/thumb/cyberkongz.gif',
      },
      {
        id: 'space-poggers',
        name: 'Space Poggers',
        symbol: 'SP',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/91/thumb/spacepoggers.jpg',
      },
      {
        id: 'tennis-champs-genesis',
        name: 'Tennis Champs Genesis',
        symbol: 'CHAMPS',
        thumb:
          'https://assets.coingecko.com/nft_contracts/images/300/thumb/tennis-champs-genesis.gif',
      },
      {
        id: 'bored-ape-comic',
        name: 'Bored Ape Comic',
        symbol: 'BAC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/100/thumb/BAC.jpg',
      },
      {
        id: 'frankfrank',
        name: 'frankfrank',
        symbol: 'FRANK',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/326/thumb/frankfrank.gif',
      },
      {
        id: 'forgotten-runes-wizards-cult',
        name: 'Forgotten Runes Wizards Cult',
        symbol: 'WIZARDS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/103/thumb/wizards.png',
      },
      {
        id: 'xrc',
        name: 'X Rabbits Club',
        symbol: 'XRC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/248/thumb/Po8VPk0Q_400x400.jpg',
      },
      {
        id: 'cometh-spaceships',
        name: 'Cometh Spaceships',
        symbol: 'SPACESHIP',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/245/thumb/unnamed.png',
      },
      {
        id: 'duskbreakers',
        name: 'DuskBreakers',
        symbol: 'DUSK',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/271/thumb/duskbreakers.png',
      },
      {
        id: 'ocm-dessert',
        name: 'OCM Dessert',
        symbol: '',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/269/thumb/ocm-desssert.gif',
      },
      {
        id: 'heavencomputer',
        name: 'HeavenComputer',
        symbol: 'HVN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/50/thumb/heavencomputer.png',
      },
      {
        id: 'alphabetty-doodles',
        name: 'AlphaBetty Doodles',
        symbol: 'ALPHABETTY',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/75/thumb/ALPHABETTY.jpg',
      },
      {
        id: 'catblox-genesis',
        name: 'CatBlox Genesis',
        symbol: 'CATBLOXGEN',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/278/thumb/catblox-genesis.png',
      },
      {
        id: 'divine-anarchy',
        name: 'Divine Anarchy',
        symbol: 'DA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/191/thumb/divineanarchy.png',
      },
      {
        id: 'crypto-raiders-characters',
        name: 'Crypto Raiders Characters',
        symbol: 'RAIDER',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/340/thumb/unnamed.png',
      },
      {
        id: 'the-currency',
        name: 'The Currency',
        symbol: 'TENDER',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/102/thumb/hirst-currency.jpg',
      },
      {
        id: 'tools-of-rock',
        name: 'Tools of Rock',
        symbol: 'TOR',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/92/thumb/TOR.png',
      },
      {
        id: 'creature-world',
        name: 'Creature World',
        symbol: 'CREATURE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/105/thumb/creatture.jpg',
      },
      {
        id: 'moondogs-odyssey',
        name: 'MOONDOGS ODYSSEY',
        symbol: 'WIENERS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/42/thumb/moondogs.jpg',
      },
      {
        id: 'dark-super-bunnies',
        name: 'Dark Super Bunnies',
        symbol: 'DSB',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/98/thumb/DSB.png',
      },
      {
        id: 'chibi-apes',
        name: 'Chibi Apes',
        symbol: 'CHIBIAPE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/176/thumb/nAdDM2QZ_400x400.jpg',
      },
      {
        id: 'fvckcrystal',
        name: 'FVCK_CRYSTAL//',
        symbol: 'CRYST',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/47/thumb/fvck-crystal.png',
      },
      {
        id: 'galaxy-eggs',
        name: 'Galaxy Eggs',
        symbol: 'GLXY',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/145/thumb/GLXY.jpg',
      },
      {
        id: 'cryptozoo-base-egg',
        name: 'CryptoZoo Base Egg',
        symbol: 'EGG',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/123/thumb/EGG.jpg',
      },
      {
        id: 'skullx',
        name: 'Skullx ',
        symbol: 'SKULLX',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/194/thumb/unnamed.gif',
      },
      {
        id: 'wizards-dragons-game',
        name: 'Wizards & Dragons Game',
        symbol: 'WND',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/204/thumb/FNcXgaZO_400x400.jpg',
      },
      {
        id: 'metakrew',
        name: 'Metakrew',
        symbol: 'METAKREW',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/205/thumb/metakrew.png',
      },
      {
        id: 'purrnelopes-country-club',
        name: 'Purrnelopes Country Club',
        symbol: 'PCC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/74/thumb/Purrnelope.jpg',
      },
      {
        id: 'abstract-loot',
        name: 'Abstract Loot',
        symbol: 'AL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/117/thumb/Abstract.png',
      },
      {
        id: 'irenedao',
        name: 'IreneDAO',
        symbol: 'IRENEDAO',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/249/thumb/RdQGuVBq_400x400.jpg',
      },
      {
        id: 'feudalz',
        name: 'Feudalz',
        symbol: 'FEUDALZ',
        thumb: 'missing_thumb.png',
      },
      {
        id: 'treeverse',
        name: 'Treeverse',
        symbol: 'TRV',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/80/thumb/treeverse.png',
      },
      {
        id: 'chain-runners',
        name: 'Chain Runners',
        symbol: 'RUN ',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/197/thumb/chainrunners.png',
      },
      {
        id: 'lost-poets',
        name: 'Lost Poets',
        symbol: 'POETS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/153/thumb/POETS.png',
      },
      {
        id: 'junkyarddogs',
        name: 'JunkYardDogs ',
        symbol: 'JYD',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/45/thumb/JYD.jpg',
      },
      {
        id: 'koala-intelligence-agency',
        name: 'Koala Intelligence Agency',
        symbol: 'KIA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/96/thumb/KIA.png',
      },
      {
        id: 'onchainmonkey',
        name: 'OnChainMonkey',
        symbol: 'OCMONK',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/213/thumb/onchain-monkey.png',
      },
      {
        id: 'anonymice',
        name: 'Anonymice',
        symbol: 'MICE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/151/thumb/MICE.png',
      },
      {
        id: 'headdao',
        name: 'HeadDAO',
        symbol: 'HEAD',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/173/thumb/NA60Aw5i_400x400.jpg',
      },
      {
        id: 'angryapesunited',
        name: 'Angry Apes United',
        symbol: 'AAU',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/187/thumb/AAU.jpg',
      },
      {
        id: 'spacepunksclub',
        name: 'SpacePunksClub',
        symbol: '⚇',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/71/thumb/SpacePunks.jpg',
      },
      {
        id: 'corruption-s',
        name: 'Corruption(s*)',
        symbol: 'CORRUPT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/192/thumb/corruptions.png',
      },
      {
        id: 'curious-addys-trading-club',
        name: "Curious Addys' Trading Club",
        symbol: 'CATC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/189/thumb/CATC.jpg',
      },
      {
        id: 'samuraisaga',
        name: 'Samurai Saga',
        symbol: 'SSAGA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/238/thumb/KMbhDiRb_400x400.jpg',
      },
      {
        id: 'byopills',
        name: 'BYOPills',
        symbol: 'BYOPILL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/27/thumb/byop.png',
      },
      {
        id: 'tom-sachs-rocket',
        name: 'Tom Sachs Rocket Components',
        symbol: 'TSRC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/76/thumb/TSRC.png',
      },
      {
        id: 'baby-battle-bots-g1',
        name: 'Baby Battle Bots G1',
        symbol: 'BBONE',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/95/thumb/BBONE.png',
      },
      {
        id: 'lil-heroes-by-edgar-plans',
        name: 'LilHeroes',
        symbol: 'LIL',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/250/thumb/pvULiRtJ_400x400.jpg',
      },
      {
        id: 'hashmasks',
        name: 'Hashmasks',
        symbol: 'HM',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/5/thumb/hashmasks.jpeg',
      },
      {
        id: 'timeless-nft',
        name: 'Timeless',
        symbol: 'TMLS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/196/thumb/timeless-nft.png',
      },
      {
        id: 'neo-tokyo-identities',
        name: 'Neo Tokyo: Identities',
        symbol: 'NEOTI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/182/thumb/neo_tokyo.png',
      },
      {
        id: 'dotdotdots',
        name: 'dotdotdots',
        symbol: 'DOTDOTDOTS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/112/thumb/DOT.png',
      },
      {
        id: 'inft-personality-pod',
        name: 'iNFT Personality Pod',
        symbol: 'POD',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/251/thumb/inft.png',
      },
      {
        id: 'crypto-unicorns',
        name: 'Crypto Unicorns',
        symbol: 'UNICORNS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/198/thumb/crypto-unicorns.png',
      },
      {
        id: 'loot',
        name: 'Loot',
        symbol: 'LOOT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/110/thumb/Loot.jpg',
      },
      {
        id: 'the-wicked-craniums',
        name: 'The Wicked Craniums',
        symbol: 'TWC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/23/thumb/the-wicked-craniums.png',
      },
      {
        id: 'mekaverse',
        name: 'MekaVerse',
        symbol: 'MEKA',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/174/thumb/CEIjdE03_400x400.jpg',
      },
      {
        id: 'merge',
        name: 'merge',
        symbol: 'M',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/217/thumb/unnamed.png',
      },
      {
        id: 'lazy-lions',
        name: 'Lazy Lions',
        symbol: 'LION',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/124/thumb/LION.png',
      },
      {
        id: 'the-sevens',
        name: 'The Sevens',
        symbol: 'SEVENS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/135/thumb/sevens.png',
      },
      {
        id: 'jenkins-the-valet',
        name: "Jenkins the Valet: The Writer's Room",
        symbol: 'JENKINS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/152/thumb/JENKINS.jpg',
      },
      {
        id: 'azuki',
        name: 'Azuki',
        symbol: 'AZUKI',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/246/thumb/azuki.jpeg',
      },
      {
        id: 'the-littles-nft',
        name: 'the littles nft',
        symbol: 'THELITTLESNFT',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/202/thumb/the-littles-nft.gif',
      },
      {
        id: 'mutant-ape-yacht-club',
        name: 'Mutant Ape Yacht Club',
        symbol: 'MAYC',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/104/thumb/mayc.png',
      },
      {
        id: 'smilesss ',
        name: 'Smilesss',
        symbol: 'SMLS',
        thumb: 'https://assets.coingecko.com/nft_contracts/images/200/thumb/k5O6mHj3_400x400.jpg',
      },
    ],
  },
};
export default searchData;
